version: '3'

services:
  mongo:
    image: mongo
    networks:
      - alati-nw
    volumes:
      - db-data:/data/db
  project:
    image: alati
    ports:
      - 80:8888
    networks:
      - alati-nw
    environment:
        articlesBlogPORT:8888
        alatiMongoUri: mongodb://mongo/alati
        alatiAdminLoginUsername: admin
        alatiAdminLoginPassword: admin

networks:
  alati-nw:
    driver: bridge

volumes:
  db-data: